# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Mindful Bit
email: erik@themindfulbit.com
description: > # this means to ignore newlines until "baseurl:"
  Looking for the intersection of mindfulness, technology, and design. Seeing the world of tech through its impermanent, emergent, and inherently unsatisfying nature. There may not be any good answers, but itâ€™s possible to have enlightening conversations around the questions the world throws at us.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: themindfulbit
github_username:  themindfulbit
permalink: /blog/:title
gems: [jekyll-paginate, jekyll-gist, rouge, jekyll-redirect-from, jekyll-sitemap]
include: ["_pages"]

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  footnote_backlink: '&#8617;&#65038;'
